/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_bewotec_playground_Reflection */

#ifndef _Included_de_bewotec_playground_Reflection
#define _Included_de_bewotec_playground_Reflection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_bewotec_playground_Reflection
 * Method:    setAccessible
 * Signature: (Ljava/lang/reflect/AccessibleObject;Z)V
 */
JNIEXPORT void JNICALL Java_de_bewotec_playground_Reflection_setAccessible
  (JNIEnv *, jclass, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
